/**
 * @jest-environment node
 *
 * Integration tests: callback API handler ↔ proxy
 * Verifies that the session token generated by the callback handler
 * is accepted by the proxy (compatible signing strategy).
 */
import {
  GET as callbackHandler,
  createSessionToken,
} from '../../app/api/auth/callback/route';
import { GET as githubHandler } from '../../app/api/auth/github/route';
import { proxy, verifySessionToken } from '../../proxy';
import { NextRequest } from 'next/server';

function makeRequest(path: string, authToken?: string): NextRequest {
  const headers: Record<string, string> = {};
  if (authToken !== undefined) {
    headers['cookie'] = `auth=${authToken}`;
  }
  return new NextRequest(`http://localhost${path}`, { headers });
}

describe('Auth flow integration', () => {
  beforeEach(() => {
    process.env.SESSION_SECRET = 'test-secret';
    process.env.GITHUB_CLIENT_ID = 'test-client-id';
    process.env.GITHUB_CLIENT_SECRET = 'test-client-secret';
    process.env.GITHUB_ALLOWED_USER = 'masaxsuzu';
    global.fetch = jest.fn();
  });

  afterEach(() => {
    jest.resetAllMocks();
  });

  describe('Token compatibility: callback ↔ proxy', () => {
    it('createSessionToken produces a token accepted by verifySessionToken', async () => {
      const token = createSessionToken('masaxsuzu');
      expect(await verifySessionToken(token)).toBe(true);
    });

    it('tampered token is rejected by verifySessionToken', async () => {
      const token = createSessionToken('masaxsuzu');
      const tampered = token.slice(0, -4) + 'ffff';
      expect(await verifySessionToken(tampered)).toBe(false);
    });

    it('token for a different user is rejected when secret differs', async () => {
      const token = createSessionToken('masaxsuzu');
      process.env.SESSION_SECRET = 'different-secret';
      expect(await verifySessionToken(token)).toBe(false);
    });
  });

  describe('GitHub OAuth initiation → callback state round-trip', () => {
    it('state cookie from github handler is accepted by callback handler', async () => {
      // Step 1: call github handler to generate state
      const githubRes = githubHandler();
      expect(githubRes.status).toBe(302);

      // Step 2: extract oauth_state from Set-Cookie
      const setCookie = githubRes.headers.get('set-cookie') ?? '';
      const stateMatch = setCookie.match(/oauth_state=([^;]+)/);
      expect(stateMatch).not.toBeNull();
      const state = stateMatch![1];

      // Step 3: pass the same state to callback — should not trigger state_mismatch
      (global.fetch as jest.Mock)
        .mockResolvedValueOnce({
          json: async () => ({ access_token: 'gh-token' }),
        })
        .mockResolvedValueOnce({
          json: async () => ({ login: 'masaxsuzu' }),
        });

      const req = new NextRequest(
        `http://localhost/api/auth/callback?code=test-code&state=${state}`,
        { headers: { cookie: `oauth_state=${state}` } }
      );
      const callbackRes = await callbackHandler(req);
      expect(callbackRes.status).toBe(302);
      expect(callbackRes.headers.get('location')).toMatch(/\/$/);
    });

    it('mismatched state from github handler is rejected by callback handler', async () => {
      // Step 1: call github handler to generate one state
      const githubRes = githubHandler();
      const setCookie = githubRes.headers.get('set-cookie') ?? '';
      const stateMatch = setCookie.match(/oauth_state=([^;]+)/);
      const state = stateMatch![1];

      // Step 2: pass a different state in the query — should trigger state_mismatch
      const req = new NextRequest(
        `http://localhost/api/auth/callback?code=test-code&state=tampered`,
        { headers: { cookie: `oauth_state=${state}` } }
      );
      const callbackRes = await callbackHandler(req);
      expect(callbackRes.status).toBe(302);
      expect(callbackRes.headers.get('location')).toContain(
        'error=state_mismatch'
      );
    });
  });

  describe('Full OAuth callback → page access flow', () => {
    it('token from successful callback is accepted by proxy', async () => {
      // Step 1: simulate successful GitHub OAuth callback
      (global.fetch as jest.Mock)
        .mockResolvedValueOnce({
          json: async () => ({ access_token: 'gh-token' }),
        })
        .mockResolvedValueOnce({
          json: async () => ({ login: 'masaxsuzu' }),
        });

      const req = new NextRequest(
        'http://localhost/api/auth/callback?code=test-code&state=test-state',
        { headers: { cookie: 'oauth_state=test-state' } }
      );
      const res = await callbackHandler(req);
      expect(res.status).toBe(302);

      // Step 2: extract auth token from the Set-Cookie header
      const setCookie = res.headers.getSetCookie().join('\n');
      const tokenMatch = setCookie?.match(/auth=([^;]+)/);
      expect(tokenMatch).not.toBeNull();
      const token = tokenMatch![1];

      // Step 3: pass token to proxy — should allow access
      const request = makeRequest('/', token);
      const proxyRes = await proxy(request);
      expect(proxyRes.status).toBe(200);
    });

    it('unauthenticated request → proxy blocks access', async () => {
      const request = makeRequest('/');
      const proxyRes = await proxy(request);
      expect(proxyRes.status).toBe(307);
      expect(proxyRes.headers.get('location')).toContain('/login');
    });

    it('tampered cookie is rejected by proxy and cleared', async () => {
      const request = makeRequest('/', 'tampered-token-value');
      const proxyRes = await proxy(request);
      expect(proxyRes.status).toBe(307);
      expect(proxyRes.headers.get('set-cookie')).toContain('auth=;');
    });

    it('authenticated user visiting /login is redirected to /', async () => {
      const token = createSessionToken('masaxsuzu');
      const request = makeRequest('/login', token);
      const proxyRes = await proxy(request);
      expect(proxyRes.status).toBe(307);
      expect(proxyRes.headers.get('location')).toMatch(/\/$/);
    });
  });
});
