/**
 * @jest-environment node
 *
 * Integration tests: login API handler ↔ middleware
 * Verifies that the token generated by the API is accepted by the middleware,
 * i.e., both modules use a compatible hashing strategy.
 */
import { createMocks } from 'node-mocks-http';
import type { NextApiRequest, NextApiResponse } from 'next';
import handler, { hashToken } from '../../pages/api/login';
import { middleware, computeExpectedToken } from '../../middleware';
import { NextRequest } from 'next/server';

function makeRequest(path: string, authToken?: string): NextRequest {
  const headers: Record<string, string> = {};
  if (authToken !== undefined) {
    headers['cookie'] = `auth=${authToken}`;
  }
  return new NextRequest(`http://localhost${path}`, { headers });
}

describe('Auth flow integration', () => {
  beforeEach(() => {
    process.env.PASSWORD = 'test-password';
    process.env.SALT = 'test-salt';
  });

  describe('Token compatibility: login API ↔ middleware', () => {
    it('hashToken and computeExpectedToken produce identical tokens for the same credentials', async () => {
      const apiToken = hashToken('test-password');
      const middlewareToken = await computeExpectedToken();
      expect(apiToken).toBe(middlewareToken);
    });

    it('tokens differ when password does not match', async () => {
      const apiToken = hashToken('wrong-password');
      const middlewareToken = await computeExpectedToken();
      expect(apiToken).not.toBe(middlewareToken);
    });

    it('tokens differ when salt differs between API and middleware', async () => {
      process.env.SALT = 'salt-for-api';
      const apiToken = hashToken('test-password');

      process.env.SALT = 'salt-for-middleware';
      const middlewareToken = await computeExpectedToken();

      expect(apiToken).not.toBe(middlewareToken);
    });
  });

  describe('Full login → page access flow', () => {
    it('token from successful login is accepted by middleware', async () => {
      // Step 1: call login API with correct password
      const { req, res } = createMocks<NextApiRequest, NextApiResponse>({
        method: 'POST',
        body: { password: 'test-password' },
      });
      handler(req, res);
      expect(res._getStatusCode()).toBe(200);

      // Step 2: extract auth token from the Set-Cookie header
      const setCookie = res._getHeaders()['set-cookie'] as string;
      const tokenMatch = setCookie.match(/auth=([^;]+)/);
      expect(tokenMatch).not.toBeNull();
      const token = tokenMatch![1];

      // Step 3: pass token to middleware — should allow access
      const request = makeRequest('/', token);
      const middlewareRes = await middleware(request);
      expect(middlewareRes.status).toBe(200);
    });

    it('failed login produces no valid cookie → middleware blocks access', async () => {
      // Step 1: call login API with wrong password → 401, no cookie set
      const { req, res } = createMocks<NextApiRequest, NextApiResponse>({
        method: 'POST',
        body: { password: 'wrong-password' },
      });
      handler(req, res);
      expect(res._getStatusCode()).toBe(401);

      // Step 2: unauthenticated request → middleware redirects to /login
      const request = makeRequest('/');
      const middlewareRes = await middleware(request);
      expect(middlewareRes.status).toBe(307);
      expect(middlewareRes.headers.get('location')).toContain('/login');
    });

    it('tampered cookie is rejected by middleware and cleared', async () => {
      const request = makeRequest('/', 'tampered-token-value');
      const middlewareRes = await middleware(request);
      expect(middlewareRes.status).toBe(307);
      expect(middlewareRes.headers.get('set-cookie')).toContain('auth=;');
    });

    it('authenticated user visiting /login is redirected to /', async () => {
      // Obtain a valid token via login API
      const { req, res } = createMocks<NextApiRequest, NextApiResponse>({
        method: 'POST',
        body: { password: 'test-password' },
      });
      handler(req, res);
      const setCookie = res._getHeaders()['set-cookie'] as string;
      const token = setCookie.match(/auth=([^;]+)/)![1];

      // Authenticated request to /login should redirect to /
      const request = makeRequest('/login', token);
      const middlewareRes = await middleware(request);
      expect(middlewareRes.status).toBe(307);
      expect(middlewareRes.headers.get('location')).toMatch(/\/$/);
    });
  });
});
