/**
 * @jest-environment node
 *
 * Integration tests: callback API handler ↔ proxy
 * Verifies that the session token generated by the callback handler
 * is accepted by the proxy (compatible signing strategy).
 */
import { createMocks } from 'node-mocks-http';
import type { NextApiRequest, NextApiResponse } from 'next';
import callbackHandler, {
  createSessionToken,
} from '../../pages/api/auth/callback';
import { proxy, verifySessionToken } from '../../proxy';
import { NextRequest } from 'next/server';

function makeRequest(path: string, authToken?: string): NextRequest {
  const headers: Record<string, string> = {};
  if (authToken !== undefined) {
    headers['cookie'] = `auth=${authToken}`;
  }
  return new NextRequest(`http://localhost${path}`, { headers });
}

describe('Auth flow integration', () => {
  beforeEach(() => {
    process.env.SESSION_SECRET = 'test-secret';
    process.env.GITHUB_CLIENT_ID = 'test-client-id';
    process.env.GITHUB_CLIENT_SECRET = 'test-client-secret';
    process.env.GITHUB_ALLOWED_USER = 'masaxsuzu';
    global.fetch = jest.fn();
  });

  afterEach(() => {
    jest.resetAllMocks();
  });

  describe('Token compatibility: callback ↔ proxy', () => {
    it('createSessionToken produces a token accepted by verifySessionToken', async () => {
      const token = createSessionToken('masaxsuzu');
      expect(await verifySessionToken(token)).toBe(true);
    });

    it('tampered token is rejected by verifySessionToken', async () => {
      const token = createSessionToken('masaxsuzu');
      const tampered = token.slice(0, -4) + 'ffff';
      expect(await verifySessionToken(tampered)).toBe(false);
    });

    it('token for a different user is rejected when secret differs', async () => {
      const token = createSessionToken('masaxsuzu');
      process.env.SESSION_SECRET = 'different-secret';
      expect(await verifySessionToken(token)).toBe(false);
    });
  });

  describe('Full OAuth callback → page access flow', () => {
    it('token from successful callback is accepted by proxy', async () => {
      // Step 1: simulate successful GitHub OAuth callback
      (global.fetch as jest.Mock)
        .mockResolvedValueOnce({
          json: async () => ({ access_token: 'gh-token' }),
        })
        .mockResolvedValueOnce({
          json: async () => ({ login: 'masaxsuzu' }),
        });

      const { req, res } = createMocks<NextApiRequest, NextApiResponse>({
        method: 'GET',
        query: { code: 'test-code' },
      });

      await callbackHandler(req, res);
      expect(res._getStatusCode()).toBe(302);

      // Step 2: extract auth token from the Set-Cookie header
      const setCookie = res._getHeaders()['set-cookie'] as string;
      const tokenMatch = setCookie.match(/auth=([^;]+)/);
      expect(tokenMatch).not.toBeNull();
      const token = tokenMatch![1];

      // Step 3: pass token to proxy — should allow access
      const request = makeRequest('/', token);
      const proxyRes = await proxy(request);
      expect(proxyRes.status).toBe(200);
    });

    it('unauthenticated request → proxy blocks access', async () => {
      const request = makeRequest('/');
      const proxyRes = await proxy(request);
      expect(proxyRes.status).toBe(307);
      expect(proxyRes.headers.get('location')).toContain('/login');
    });

    it('tampered cookie is rejected by proxy and cleared', async () => {
      const request = makeRequest('/', 'tampered-token-value');
      const proxyRes = await proxy(request);
      expect(proxyRes.status).toBe(307);
      expect(proxyRes.headers.get('set-cookie')).toContain('auth=;');
    });

    it('authenticated user visiting /login is redirected to /', async () => {
      const token = createSessionToken('masaxsuzu');
      const request = makeRequest('/login', token);
      const proxyRes = await proxy(request);
      expect(proxyRes.status).toBe(307);
      expect(proxyRes.headers.get('location')).toMatch(/\/$/);
    });
  });
});
